name: term-matching-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - spacy
  - gensim
  - pip
  - pip:
      - setuptools
      - openpyxl
      - gspread
      - oauth2client
      - sentence-transformers
      - fuzzywuzzy[speedup]
  - spacy-model-en_core_web_lg