name: term-matching-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - gensim
  - pandas
  - pip
  - pip:
    - torch
    - openpyxl
    - transformers
    - sentence-transformers
    #- spacy We dont use this model anymore
    - scikit-learn
    - git-lfs