name: term-matching-env
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - ca-certificates=2024.7.2
  - catalogue=2.0.10
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - confection=0.1.4
  - cymem=2.0.6
  - cython-blis=0.7.9
  - gensim=4.3.2
  - icc_rt=2022.1.0
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - langcodes=3.3.0
  - libffi=3.4.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - murmurhash=1.0.7
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.14
  - packaging=24.1
  - pandas=2.0.3
  - pathy=0.10.3
  - pip=24.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - preshed=3.0.6
  - pydantic=1.10.12
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - requests=2.32.3
  - scipy=1.10.1
  - setuptools=72.1.0
  - shellingham=1.5.0
  - six=1.16.0
  - smart_open=5.2.1
  - spacy=3.5.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - spacy-model-en_core_web_lg=3.5.0
  - spacy-model-en_core_web_md=3.5.0
  - sqlite=3.45.3
  - srsly=2.4.8
  - tbb=2021.8.0
  - thinc=8.1.10
  - tqdm=4.66.4
  - typer=0.4.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wasabi=0.9.1
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - pip:
      - cachetools==5.4.0
      - et-xmlfile==1.1.0
      - filelock==3.15.4
      - fsspec==2024.6.1
      - fuzzywuzzy==0.18.0
      - google-auth==2.32.0
      - google-auth-oauthlib==1.2.1
      - gspread==6.1.2
      - httplib2==0.22.0
      - huggingface-hub==0.24.5
      - joblib==1.4.2
      - levenshtein==0.25.1
      - mpmath==1.3.0
      - networkx==3.1
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - openpyxl==3.1.5
      - pillow==10.4.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyparsing==3.1.2
      - python-levenshtein==0.25.1
      - pyyaml==6.0.1
      - rapidfuzz==3.9.5
      - regex==2024.7.24
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - safetensors==0.4.4
      - scikit-learn==1.3.2
      - sentence-transformers==3.0.1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.4.0
      - transformers==4.44.0